[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ticker_token = "EjJFMSVeNQYjjJJkC3fic9pTHj9AcowTbEz7CcGFkXXk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
